name: .NET

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Restore dependencies
      run: |
        dotnet restore src/S7CommPlusDriver
        dotnet restore src/DriverTest
        dotnet restore src/S7CommPlusGUIBrowser

    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ github.event.release.tag_name }}
        assemblyVersion: ${{ github.event.release.tag_name }}
        fileVersion: ${{ github.event.release.tag_name }}
        informationalVersion: ${{ github.event.release.tag_name }}-${{ github.sha }}
    
    - name: Build
      run: |
        dotnet build --configuration Release src/S7CommPlusDriver
        dotnet build --configuration Release src/DriverTest
        dotnet build --configuration Release src/S7CommPlusGUIBrowser
    - name: Publish
      run: |
        dotnet nuget push src/S7CommPlusDriver/bin/Release/*.nupkg
